# Generated by Django 3.1.7 on 2021-03-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seller'),
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
