# Generated by Django 3.1.7 on 2021-03-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210326_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='packingCost',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='shippingCost',
        ),
        migrations.AddField(
            model_name='expense',
            name='moneySpent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
