# Generated by Django 3.1.7 on 2021-04-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210413_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('SHOE', 'Shoe'), ('CARD', 'Card')], max_length=100, null=True),
        ),
    ]
