# Generated by Django 3.1.7 on 2021-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='brand',
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
