# Generated by Django 3.1.7 on 2021-04-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210415_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='moneySpent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
